[versions]
root = "2.0.0-rc1"
foundation = "1.5.2"

[libraries]
expect-core = { module = "tz.co.asoft:expect-core", version.ref = "foundation" }
expect-coroutines = { module = "tz.co.asoft:expect-coroutines", version.ref = "foundation" }

functions = { module = "tz.co.asoft:functions", version.ref = "foundation" }

koncurrent-primitives-core = { module = "tz.co.asoft:koncurrent-primitives-core", version.ref = "foundation" }
koncurrent-primitives-coroutines = { module = "tz.co.asoft:koncurrent-primitives-coroutines", version.ref = "foundation" }
koncurrent-primitives-mock = { module = "tz.co.asoft:koncurrent-primitives-mock", version.ref = "foundation" }

kotlinx-browser = { module = "tz.co.asoft:kotlinx-browser", version.ref = "foundation" }
kotlinx-collections-atomic = { module = "tz.co.asoft:kotlinx-collections-atomic", version.ref = "foundation" }
kotlinx-collections-interoperable = { module = "tz.co.asoft:kotlinx-collections-interoperable", version.ref = "foundation" }

logging-console = { module = "tz.co.asoft:logging-console", version.ref = "foundation" }
logging-test-android = { module = "tz.co.asoft:logging-test-android", version.ref = "foundation" }

[plugins]
applikation = { id = "tz.co.asoft.applikation", version.ref = "foundation" }
library = { id = "tz.co.asoft.library", version.ref = "foundation" }
deploy = { id = "tz.co.asoft.deploy", version.ref = "foundation" }